fix: Cleanup duplicated wiki entries - MEED-10114 - Meeds-io/meeds#3924 (#1585)
Prior to this change, for some reason, on some instances some wiki
entrees are duplicated on OWNER,TYPE attributes for WIKI_WIKIS table
despite of unique constraint on those columns added by changeSet of
id="1.0.0-54". This makes this kind of exception:
`ChangeSet db/changelog/wiki.db.changelog-1.0.0.xml::1.0.0-54::wiki
encountered an exception. [liquibase.changelog.ChangeSet]
liquibase.exception.DatabaseException: Duplicate entry
'nessrineberrama-user' for key 'WIKI_WIKIS.UK_WIKI_WIKIS_OWNER_TYPE_01'
[Failed SQL: (1062) ALTER TABLE community.WIKI_WIKIS ADD CONSTRAINT
UK_WIKI_WIKIS_OWNER_TYPE_01 UNIQUE (OWNER, TYPE)].` After this commit,
we added a changeset of
id="1.0.0-53-clean-duplicates" which will be executed before changeset
1.0.0-54 in order to clean these duplicated entries and let the next
changesets to be executed normally.

Resolves meeds-io/meeds#3924